import type {
  EventItem,
  Hotel,
  TransportOption,
  Trip,
} from "./types";
import { money } from "./money";

// ── Unsplash placeholder helper ───────────────────────────────
const img = (id: string, w = 1200) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

const avatar = (n: number) => `https://i.pravatar.cc/120?img=${n}`;

// ─────────────────────────────────────────────────────────────
// EVENTS
// ─────────────────────────────────────────────────────────────
export const events: EventItem[] = [
  {
    id: "neon-pulse",
    slug: "neon-pulse",
    title: "Neon Pulse Music Festival 2025",
    category: "Concerts",
    date: "Dec 14, 2025",
    isoDate: "2025-12-14",
    time: "8:00 PM",
    venue: "Madison Square Garden",
    city: "New York",
    image: img("photo-1470229722913-7c0e2dbbafd3"),
    price: money(85),
    rating: 4.9,
    reviewCount: 2100,
    attendees: 12,
    host: "LiveNation Presents",
    onSale: true,
    capacity: 12000,
    description:
      "Neon Pulse returns for its biggest year yet — a full night of electronic energy across three stages, immersive light installations, and headline sets from the artists defining the sound of tomorrow. Doors open at 7:00 PM. Expect pyrotechnics, surprise guests, and a closing set you'll be talking about for months.",
    genres: ["EDM", "Pop", "Hip Hop", "Dance", "House"],
    artists: [
      { id: "a1", name: "DJ Maverick", avatar: avatar(11) },
      { id: "a2", name: "Luna Wave", avatar: avatar(5) },
      { id: "a3", name: "Rex Volta", avatar: avatar(12) },
      { id: "a4", name: "Zara Neon", avatar: avatar(9) },
      { id: "a5", name: "Marco K.", avatar: avatar(13) },
    ],
    ticketTiers: [
      {
        id: "ga",
        name: "General Admission",
        price: money(85),
        description: "Standing access to the main floor",
        perks: ["Main floor access", "Re-entry permitted"],
        available: 1200,
        refundable: false,
        transferable: true,
      },
      {
        id: "vip",
        name: "VIP Experience",
        price: money(245),
        description: "Elevated viewing + perks",
        perks: ["VIP viewing deck", "Open bar", "Artist meet & greet"],
        available: 48,
        refundable: true,
        transferable: true,
      },
      {
        id: "platinum",
        name: "Platinum Package",
        price: money(580),
        description: "The ultimate night out",
        perks: ["Private suite", "Limo transfer", "Backstage tour", "Open bar"],
        available: 12,
        refundable: true,
        transferable: false,
      },
      {
        id: "student",
        name: "Student Pass",
        price: money(45),
        description: "Valid student ID required at entry",
        perks: ["Main floor access"],
        available: 0,
        refundable: false,
        transferable: false,
      },
    ],
    reviews: [
      {
        id: "r1",
        author: "Priya S.",
        avatar: avatar(20),
        rating: 5,
        date: "2 weeks ago",
        body: "Absolutely electric. The light show during Luna Wave's set was unreal. Already got tickets for next year.",
      },
      {
        id: "r2",
        author: "Daniel R.",
        avatar: avatar(33),
        rating: 5,
        date: "1 month ago",
        body: "VIP was worth every cent — the open bar and meet & greet made it a night to remember.",
      },
    ],
  },
  {
    id: "global-tech-summit",
    slug: "global-tech-summit",
    title: "Global Tech Summit",
    category: "Tech",
    date: "Nov 8, 2025",
    isoDate: "2025-11-08",
    time: "9:00 AM",
    venue: "Moscone Center",
    city: "San Francisco",
    image: img("photo-1540575467063-178a50c2df87"),
    price: money(120),
    rating: 4.7,
    reviewCount: 860,
    attendees: 48,
    host: "Summit Group",
    onSale: true,
    description:
      "Two days of keynotes, deep-dive workshops, and networking with the builders shaping AI, cloud, and the future of software.",
    genres: ["AI", "Cloud", "Startups"],
  },
  {
    id: "summer-bloom",
    slug: "summer-bloom",
    title: "Summer Bloom Festival",
    category: "Festivals",
    date: "Jul 19, 2025",
    isoDate: "2025-07-19",
    time: "12:00 PM",
    venue: "Golden Gate Park",
    city: "San Francisco",
    image: img("photo-1533174072545-7a4b6ad7a6c3"),
    price: null,
    rating: 4.6,
    reviewCount: 410,
    attendees: 230,
    host: "City Parks Dept.",
  },
  {
    id: "nba-all-star",
    slug: "nba-all-star",
    title: "NBA All-Star Game",
    category: "Sports",
    date: "Feb 16, 2025",
    isoDate: "2025-02-16",
    time: "7:30 PM",
    venue: "Chase Center",
    city: "San Francisco",
    image: img("photo-1546519638-68e109498ffc"),
    price: money(240),
    rating: 4.8,
    reviewCount: 1500,
    attendees: 64,
    host: "NBA",
    onSale: true,
  },
  {
    id: "jazz-blues-night",
    slug: "jazz-blues-night",
    title: "Jazz & Blues Night",
    category: "Concerts",
    date: "Oct 3, 2025",
    isoDate: "2025-10-03",
    time: "8:30 PM",
    venue: "Blue Note",
    city: "New York",
    image: img("photo-1511192336575-5a79af67a629"),
    price: money(55),
    rating: 4.9,
    reviewCount: 320,
    attendees: 18,
    host: "Blue Note Jazz Club",
  },
  {
    id: "design-leadership",
    slug: "design-leadership",
    title: "Design Leadership Bootcamp",
    category: "Workshops",
    date: "Sep 12, 2025",
    isoDate: "2025-09-12",
    time: "10:00 AM",
    venue: "Online + Brooklyn Studio",
    city: "Brooklyn",
    image: img("photo-1531403009284-440f080d1e12"),
    price: null,
    rating: 4.5,
    reviewCount: 140,
    attendees: 36,
    host: "DesignOps Collective",
  },
  {
    id: "modern-art-gala",
    slug: "modern-art-gala",
    title: "Modern Art Gala",
    category: "Arts",
    date: "Dec 1, 2025",
    isoDate: "2025-12-01",
    time: "6:00 PM",
    venue: "The Met",
    city: "New York",
    image: img("photo-1499781350541-7783f6c6a0c8"),
    price: money(40),
    rating: 4.7,
    reviewCount: 220,
    attendees: 90,
    host: "Metropolitan Museum",
  },
  {
    id: "nyc-marathon",
    slug: "nyc-marathon",
    title: "NYC Marathon",
    category: "Sports",
    date: "Nov 2, 2025",
    isoDate: "2025-11-02",
    time: "8:00 AM",
    venue: "Five Boroughs",
    city: "New York",
    image: img("photo-1452626038306-9aae5e071dd3"),
    price: money(30),
    rating: 4.9,
    reviewCount: 980,
    attendees: 0,
    host: "NYRR",
    soldOut: true,
  },
];

export function getEvent(slug: string): EventItem | undefined {
  return events.find((e) => e.slug === slug || e.id === slug);
}

export const featuredEvents = events.filter((e) =>
  ["neon-pulse", "nba-all-star", "modern-art-gala", "global-tech-summit"].includes(e.id),
);

export const recommendedEvents = events.filter((e) =>
  ["jazz-blues-night", "summer-bloom", "design-leadership"].includes(e.id),
);

// ─────────────────────────────────────────────────────────────
// TRANSPORT
// ─────────────────────────────────────────────────────────────
export const transportOptions: TransportOption[] = [
  {
    id: "ua2045",
    mode: "flight",
    icon: "✈️",
    carrier: "United Airlines",
    code: "UA 2045",
    origin: "Los Angeles",
    originCode: "LAX",
    destination: "New York",
    destinationCode: "JFK",
    depart: "07:30",
    arrive: "15:55",
    duration: "5h 25m",
    stops: 0,
    price: money(289),
    tag: "best",
    note: "Arrives 3h before show — perfect buffer. Carry-on included.",
    noteTone: "positive",
    recommended: true,
  },
  {
    id: "amtrak2151",
    mode: "train",
    icon: "🚂",
    carrier: "Amtrak",
    code: "#2151",
    origin: "Los Angeles",
    originCode: "LAX",
    destination: "New York",
    destinationCode: "NYP",
    depart: "10:00",
    arrive: "05:45 (+3d)",
    duration: "67h 45m",
    stops: 2,
    price: money(149),
    note: "Not recommended — arrives well after the event.",
    noteTone: "danger",
  },
  {
    id: "nk1074",
    mode: "flight",
    icon: "✈️",
    carrier: "Spirit Airlines",
    code: "NK 1074",
    origin: "Los Angeles",
    originCode: "LAX",
    destination: "New York",
    destinationCode: "JFK",
    depart: "12:15",
    arrive: "19:15",
    duration: "7h 00m",
    stops: 1,
    price: money(189),
    note: "Tight arrival — 45min before showtime.",
    noteTone: "warning",
  },
];

// ─────────────────────────────────────────────────────────────
// HOTELS
// ─────────────────────────────────────────────────────────────
export const hotels: Hotel[] = [
  {
    id: "grand-plaza",
    name: "Grand Plaza Hotel",
    image: img("photo-1566073771259-6a8506099945", 800),
    rating: 4.8,
    distance: "0.4 mi from venue",
    pricePerNight: money(185),
    amenities: ["wifi", "pool", "gym", "breakfast"],
  },
  {
    id: "shinjuku-granbell",
    name: "Shinjuku Granbell",
    image: img("photo-1551882547-ff40c63fe5fa", 800),
    rating: 4.6,
    distance: "0.6 mi from station",
    pricePerNight: money(140),
    amenities: ["wifi", "bar", "gym"],
  },
];

// ─────────────────────────────────────────────────────────────
// TRIP (Dashboard)
// ─────────────────────────────────────────────────────────────
export const trip: Trip = {
  id: "tokyo-kyoto-run",
  name: "Tokyo & Kyoto Run",
  days: 7,
  stops: 2,
  hotels: 3,
  flights: 4,
  dateRange: "Apr 14, 2025 — Apr 21, 2025",
  itinerary: [
    {
      day: 1,
      label: "DAY 1",
      items: [
        {
          id: "d1-1",
          kind: "transport",
          time: "06:30",
          title: "Depart Tokyo Narita (NRT)",
          subtitle: "Terminal 2, Gate 38",
        },
        {
          id: "d1-2",
          kind: "event",
          time: "10:00",
          title: "Senso-ji Temple Visit",
          subtitle: "Asakusa, Taito City, Tokyo",
        },
        {
          id: "d1-3",
          kind: "stay",
          time: "15:00",
          title: "Check-in Shinjuku Granbell",
          subtitle: "2-14-5 Kabukicho, Shinjuku",
        },
        {
          id: "d1-4",
          kind: "food",
          time: "19:30",
          title: "Dinner — Ichiran Ramen Shibuya",
          subtitle: "1-22-7 Jinnan, Shibuya City",
        },
      ],
    },
    {
      day: 2,
      label: "DAY 2",
      items: [
        {
          id: "d2-1",
          kind: "transport",
          time: "08:00",
          title: "Shinkansen to Kyoto",
          subtitle: "Tokyo Station → Kyoto Station",
        },
        {
          id: "d2-2",
          kind: "event",
          time: "11:30",
          title: "Fushimi Inari Shrine",
          subtitle: "68 Fukakusa Yabunouchicho",
        },
        {
          id: "d2-3",
          kind: "stay",
          time: "16:00",
          title: "Check-in Kyoto Machiya",
          subtitle: "Gion District",
        },
      ],
    },
    {
      day: 3,
      label: "DAY 3",
      items: [
        {
          id: "d3-1",
          kind: "event",
          time: "09:00",
          title: "Arashiyama Bamboo Grove",
          subtitle: "Ukyo Ward, Kyoto",
        },
        {
          id: "d3-2",
          kind: "food",
          time: "13:00",
          title: "Kaiseki Lunch",
          subtitle: "Pontocho Alley",
        },
      ],
    },
    {
      day: 4,
      label: "DAY 4",
      items: [
        {
          id: "d4-1",
          kind: "transport",
          time: "07:45",
          title: "Return Shinkansen to Tokyo",
          subtitle: "Kyoto Station → Tokyo Station",
        },
      ],
    },
  ],
};